### ISSUE TITLE
KeyError: 'found'

### ISSUE THREAD

**Issue by Mysteriza** [JackJuly/linkook#2]
I get this error when I run it in WSL (Kali Linux) on Windows 11 (I don't know if this affects it). for the record, I have installed the requirements correctly.
![Image](https://github.com/user-attachments/assets/33d6e64a-3b1c-445e-a5fe-e4585711d4ea)

```
Traceback (most recent call last):
  File "/home/mysteriza/.local/bin/linkook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mysteriza/.local/lib/python3.12/site-packages/linkook/linkook.py", line 291, in main
    results = scan_queue(username, scanner, console_printer, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysteriza/.local/lib/python3.12/site-packages/linkook/linkook.py", line 199, in scan_queue
    "status": "FOUND" if scan_result["found"] else "NOT FOUND",
                         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'found'
```

**Comment by JackJuly** [comment]
Looks like bugs. I will look into it. Thanks for reporting ☀️

**Comment by JackJuly** [comment]
Hi, I fixed some bugs, don't know if it solved this. Cloud you provide your command?

**Comment by Mysteriza** [comment]
The command is simple:
```
linkook mysteriza --show-summary
```
But it also happens without --show-summary too.

**Comment by Mysteriza** [comment]
I have tested it, the error still occurs with the command I mentioned above. but when I use other commands such as:
```
linkook mysteriza --check-breach --scan-all --silent
```
it works perfectly! The only problem is --show-summary which somehow shows an error.

**Comment by JackJuly** [comment]
Already fix this bug. You can try it again. ☀️

**Comment by obananazo** [comment]
@JackJuly You seem to use dicts with defaults correctly for most of the result output. Why not for `status` as well? This way you can avoid key errors like this one.

```py
# Notify results to console
  if not args.silent:
      console_printer.update(
          {
              "site_name": provider_name,
              "status": "FOUND" if scan_result["found"] else "NOT FOUND",
              "profile_url": scan_result["profile_url"],
              "other_links": scan_result.get("other_links", {}),
              "other_links_flag": other_links_flag,
              "infos": scan_result.get("infos", {}),
          }
      )
```

**Comment by Mysteriza** [comment]
It's already working, by the way. Thanks for the fix. Hopefully this tool can grow more and more!

For reference, you might know the [Maigret](https://github.com/soxoj/maigret) tool, I think it's also cool for you to implement some of its features in this tool.

**Comment by JackJuly** [comment]
> It's already working, by the way. Thanks for the fix. Hopefully this tool can grow more and more!
> 
> For reference, you might know the [Maigret](https://github.com/soxoj/maigret) tool, I think it's also cool for you to implement some of its features in this tool.

Thanks for the sharing. I will look into this tool 😊

**Comment by JackJuly** [comment]
> [@JackJuly](https://github.com/JackJuly) You seem to use dicts with defaults correctly for most of the result output. Why not for `status` as well? This way you can avoid key errors like this one.
> 
> # Notify results to console
>   if not args.silent:
>       console_printer.update(
>           {
>               "site_name": provider_name,
>               "status": "FOUND" if scan_result["found"] else "NOT FOUND",
>               "profile_url": scan_result["profile_url"],
>               "other_links": scan_result.get("other_links", {}),
>               "other_links_flag": other_links_flag,
>               "infos": scan_result.get("infos", {}),
>           }
>       )
> What I mean is that instead of
> 
> "status": "FOUND" if scan_result["found"] else "NOT FOUND",`
> I'd recommend using
> 
> scan_result.get("found", "NOT FOUND")

Nice suggestion😊 I found the bug comes from the `site_scanner.py`. Yours can also solve this.  Thanks ☀️☀️☀️
